[package]
name = "notice-test"
version = "0.1.0"
authors = ["Sam Wilson <tecywiz121@hotmail.com>"]
license = "MPL-2.0"
description = "Common tests for all notice implementations"

[dependencies]
notice-core = { version = "0.1.0", path = "../notice-core" }
