[package]
name = "notice-core"
version = "0.1.0"
authors = ["Sam Wilson <tecywiz121@hotmail.com>"]
license = "MPL-2.0"
description = "Traits and some implementations for notify/wait pattern"

[dependencies]
